# Generated by Django 4.1.4 on 2022-12-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team1',
            name='image',
        ),
    ]
