# Generated by Django 4.1.4 on 2022-12-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_team1_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team1',
            name='image',
            field=models.ImageField(default=' ', upload_to='team/'),
            preserve_default=False,
        ),
    ]
