# Generated by Django 4.1.4 on 2022-12-30 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_team1_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team1',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
