# Generated by Django 4.1.4 on 2023-01-06 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_category_team1_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team1',
            old_name='Category',
            new_name='category',
        ),
    ]
