# Generated by Django 4.1.4 on 2023-01-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(help_text='Uplode your CV', upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='type',
            field=models.CharField(choices=[('Coding', 'Coding'), ('Design', 'Design')], max_length=15),
        ),
    ]
