# Generated by Django 4.1.4 on 2023-01-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_cv_alter_education_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='year',
            field=models.IntegerField(),
        ),
    ]
